Repository jabardigitalservice/portal-jabar-cms, pull requests merged in 2022-01, with the labels that each got.

#18 feat: Agenda List View
  package-lock.json
  package.json
  src/assets/styles/tailwind.css
  src/components/Agenda/AgendaTable.vue
  src/components/Agenda/index.vue
  src/lib/date-fns.js
  src/repositories/RepositoryFactory.js
  src/repositories/agendaRepository.js
Labels: enhancement, feature

#10 feat: add refresh token
  .eslintrc.js
  src/main.js
  src/repositories/Repository.js
  src/repositories/authRepository.js
  src/store/modules/auth.js
  src/store/subscriber.js
Labels: feature

#22 feat: add create agenda page layout
  .eslintrc.js
  src/assets/icons/link.svg
  src/components/Agenda/CreateAgenda.vue
  src/pages/AgendaPage/CreateAgendaPage.vue
  src/pages/AgendaPage/index.vue
  src/router/routes.js
  src/static/data/index.js
Labels: feature

#23 chore: Agenda Detail Layout
  .eslintrc.js
  src/components/Agenda/AgendaDetail.vue
  src/components/ui/BaseButton.vue
  src/components/ui/Header.vue
  src/components/ui/HeaderMenu.vue
  src/pages/AgendaDetailPage.vue
  src/router/routes.js
Labels: enhancement, feature

#26 feat: agenda detail preview
  src/assets/icons/calendar-green.svg
  src/assets/icons/category-green.svg
  src/assets/icons/link-green.svg
  src/assets/icons/marker-green.svg
  src/assets/icons/tag-green.svg
  src/components/Agenda/AgendaDetail.vue
  src/components/Agenda/AgendaPreview.vue
  src/lib/date-fns.js
Labels: enhancement, feature

#29 feat: modal transition
  src/components/ui/BaseModal.vue
  tailwind.config.js
Labels: enhancement

#30 feat: agenda list preview
  src/components/Agenda/AgendaTable.vue
  src/components/Agenda/AgendaTableAction.vue
  src/components/Agenda/index.vue
Labels: enhancement, feature

#32 feat: delete agenda
  src/components/Agenda/AgendaDetail.vue
  src/components/Agenda/AgendaTable.vue
  src/components/Agenda/AgendaTableAction.vue
  src/components/Agenda/index.vue
  src/components/ui/BaseButton.vue
  src/repositories/agendaRepository.js
Labels: enhancement, feature

#41 refactor: improve base button
  src/components/Agenda/AgendaDetail.vue
  src/components/Agenda/AgendaForm.vue
  src/components/Agenda/index.vue
  src/components/Login/ForgotPassword.vue
  src/components/ui/BaseButton.vue
  src/components/ui/BaseModal.vue
  src/components/ui/Header.vue
  src/components/ui/HeaderMenu.vue
Labels: enhancement
